[package]
name = "rust_flashcard"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
